# Generated by Django 3.2.4 on 2021-06-27 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myid', models.CharField(max_length=20, unique=True)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('myid', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=15)),
                ('p_class', models.CharField(max_length=30)),
                ('p_race', models.CharField(max_length=30)),
                ('power', models.IntegerField()),
                ('status', models.IntegerField()),
                ('temp_power', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='game.game')),
            ],
        ),
    ]
